#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to DigitalOcean's 1-Click Pangolin Droplet.
To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (HTTP), 443 (HTTPS), and 51820 (WireGuard).

In a web browser, after completing setup, you can access:
 * The Pangolin Dashboard: https://YOUR_DOMAIN
 * Documentation: https://docs.fossorial.io

On first login, you'll be guided through the Pangolin setup process to:
 1. Configure your domain
 2. Set up SSL certificates
 3. Complete the installation

For help and more information, visit: https://github.com/fosrl/pangolin
Or join the community: https://discord.gg/HCJR8Xhme4

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF